### ISSUE TITLE
CI failing with image_common

### ISSUE THREAD

**Issue by vmayoral** [AcutronicRobotics/moveit2#27]
@LanderU according to https://travis-ci.org/AcutronicRobotics/moveit2/jobs/503697295 we seem to have an issue with `image_common`, right? I guess this comes from a requirement related to https://github.com/AcutronicRobotics/moveit2/pull/26?

**Comment by LanderU** [comment]
Yes, I'm working on it.

**Comment by LanderU** [comment]
Linux master branch: https://travis-ci.org/AcutronicRobotics/moveit2/jobs/503995410

**Comment by LanderU** [comment]
OS X master branch: https://travis-ci.org/AcutronicRobotics/moveit2/jobs/503995411

**Comment by LanderU** [comment]
Fixed on master: https://travis-ci.org/AcutronicRobotics/moveit2/builds/503995409, I'm going to fix it on perception branch as well.

**Comment by LanderU** [comment]
Fixed on perception for Linux: https://travis-ci.org/AcutronicRobotics/moveit2/jobs/504057073

**Comment by LanderU** [comment]
Fixed on perception for OS X: https://travis-ci.org/AcutronicRobotics/moveit2/jobs/504079320

**Comment by LanderU** [comment]
Everything working, perception branch status: https://travis-ci.org/AcutronicRobotics/moveit2/builds/504079318

**Comment by vmayoral** [comment]
Thanks a lot @LanderU
