### ISSUE TITLE
MoveIt 2 logo

### ISSUE THREAD

**Issue by vmayoral** [AcutronicRobotics/moveit2#33]
For upcoming announcements, we should use a different logo than the MoveIt! one. @davetcoleman and @mlautman, feel free to add your views and comment on this. 
To accelerate this, @izamalloa, can you please slightly modify 

![](https://camo.githubusercontent.com/10f367f605e5125f34778adfdc5ec47f70986358/687474703a2f2f6d6f766569742e726f732e6f72672f6173736574732f696d616765732f6d6f76656974325f6c6f676f5f626c61636b2e706e67)

with the following requests (_I'll be editing this based on the input we receive_):
1. Replace the `MoveIt!` with `MoveIt 2`

**Comment by vmayoral** [comment]
@lalzolak please coordinate this.

**Comment by izamalloa** [comment]
Here some prototypes. Once we decide the line to follow, I **will improve it** and create different types of images.
![image](https://user-images.githubusercontent.com/10087132/54906817-607fa980-4ee4-11e9-9883-74b227bcc9bd.png)

**Comment by vmayoral** [comment]
I'd say we go for the second one @izamalloa but you're the design expert so feel free to make the final choice yourself. Also, can you please ensure that the colours are the exact same ones as the ones in the existing logo (I see the blue color is different). Refer to https://moveit.ros.org/ if you need to review them.

Can you put all the design files in https://drive.google.com/drive/u/2/folders/1n506AcayaQKrdhpnu_-CfORDjWSGsAlq so that we can distribute them if required by the community?

**Comment by izamalloa** [comment]
Uploaded the [logo in different formats](https://drive.google.com/open?id=1n506AcayaQKrdhpnu_-CfORDjWSGsAlq).

**Comment by vmayoral** [comment]
Great, thanks a lot @izamalloa.

**Comment by robroboto** [comment]
Hi all, we will be releasing the new official MoveIt logos shortly and publishing them to the MoveIt website. Stay tuned :)

**Comment by vmayoral** [comment]
Thanks Rob, let us know when available.

**Comment by robroboto** [comment]
Hi all, I've uploaded all the new logos here in the short term: https://drive.google.com/drive/folders/1iOpbikPiZw3ZmjHT42fphujMKzcDWvGk?usp=sharing

We'll add to the MoveIt website in the near future as there are several ongoing website sprints ongoing at the moment.

Thanks!

Rob
