### ISSUE TITLE
CI multi-OS (enable OS X also)

### ISSUE THREAD

**Issue by vmayoral** [AcutronicRobotics/moveit2#4]
Motivated by #3 I'm considering whether it'll make sense to at least have CI also enabled for OS X.

I quickly checked and it seems it's feasible https://stackoverflow.com/questions/19818336/how-to-make-travis-ci-test-package-for-linux-os-x-windows.

**Comment by vmayoral** [comment]
@LanderU, I saw https://github.com/AcutronicRobotics/moveit2/tree/ci-new, is this branch including OS X support? 

I just fixed master branch with some OS X-related errors. See https://github.com/AcutronicRobotics/moveit2/commit/c33b95cc53501ca4fb2c2e6bbfe243ee19935ec0

**Comment by LanderU** [comment]
Not yet, I'm working to have minimal version on Linux working first. I'm reviewing/porting all the stuff. When I finish with this I'll include the OS X support as well.

**Comment by vmayoral** [comment]
Cool, many thanks.

**Comment by LanderU** [comment]
CI enabled for OS X on master.
