### ISSUE TITLE
rosdep not working properly

### ISSUE THREAD

**Issue by LanderU** [AcutronicRobotics/moveit2#63]
Issue on ros-infrastructure: https://github.com/ros-infrastructure/rosdep/issues/677

**Comment by vmayoral** [comment]
Thanks for reporting @LanderU

**Comment by LanderU** [comment]
These commits should fix the issue:

* https://github.com/AcutronicRobotics/moveit_ci/commit/d403158394a68be06e01cbb7b4ea20c8cb7a64b7
* https://github.com/AcutronicRobotics/moveit_ci/commit/ebcc93ba7e768fc304401b243eebcfb9f51e5af6

**Comment by ahcorde** [comment]
Thanks @LanderU
