### ISSUE TITLE
External dependencies with .repos file

### ISSUE THREAD

**Issue by LanderU** [AcutronicRobotics/moveit2#7]
I'll create a .repos file for external dependencies. I think using this method can help us on the development.

I'll take care of this if you are agree @vmayoral and @anasarrak.

**Comment by anasarrak** [comment]
Sure!!! anything you need just ask it!

**Comment by LanderU** [comment]
https://github.com/AcutronicRobotics/moveit2/commit/303eac9a316b8206c8432c54cac39494a3f45c09

**Comment by LanderU** [comment]
I'll setup correctly the Dockerfile for CI.

**Comment by vmayoral** [comment]
@LanderU you may want to look at https://travis-ci.org/AcutronicRobotics/moveit2/builds/494582495?utm_source=github_status&utm_medium=notification

I think something's quite not working still

**Comment by LanderU** [comment]
There is a typo on this Dockerfile. `4(nproc)`. This branch is out-date. I've fixed several things in current master.

**Comment by LanderU** [comment]
I'll fix for you the rest of the branches.
