### ISSUE TITLE
CI for Dashing

### ISSUE THREAD

**Issue by vmayoral** [AcutronicRobotics/moveit2#76]
Together with https://github.com/AcutronicRobotics/moveit2/issues/68, can we try and address the CI @ahcorde and @anasarrak?

**Comment by LanderU** [comment]
I've plan to do it over the weekend.

**Comment by vmayoral** [comment]
Great, thanks

**Comment by LanderU** [comment]
Finally I'm been able to compile the dependencies for moveit2! for dashing. We need to rework part of the things. Also, the branches on moveit2.repos are not well set. WIP!

**Comment by vmayoral** [comment]
@LanderU and @ahcorde I can see things are building now. Can we close this issue then?

**Comment by LanderU** [comment]
Sure!
